import os
import datetime
from time import strftime
from playsound import playsound
print("-Every 15 minutes")
print("-Every 30 minutes")
print("-Every 60 minutes")
x = int(input("Enter number of minutes to chime:"))
print("Running...")
while x == 15:
    print(strftime("%H:%M:%S"), end="", flush=x)
    print("\r", end="", flush=x)
    if 1 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 1 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 1 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 1 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 2 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 2 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 2 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 2 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 3 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 3 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 3 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 3 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 4 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 4 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 4 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 4 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 5 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 5 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 5 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 5 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 6 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 6 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 6 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 6 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 7 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 7 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 7 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 7 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 8 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 8 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 8 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 8 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 9 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 9 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 9 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 9 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 10 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 10 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 10 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 10 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 11 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 11 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 11 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 11 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 12 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 12 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 12 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 12 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 13 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 13 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 13 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 13 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 14 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 14 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 14 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 14 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 15 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 15 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 15 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 15 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 16 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 16 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 16 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 16 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 17 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 17 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 17 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 17 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 18 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 18 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 18 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 18 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 19 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 19 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 19 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 19 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 20 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 20 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 20 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 20 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 21 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 21 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 21 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 21 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 22 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 22 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 22 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 22 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 23 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 23 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 23 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 23 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 00 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 00 == datetime.datetime.now().hour and 15 == datetime.datetime.now().minute:
        playsound('Quarter Hour Chime.mp3')
        playsound('#.mp3')
    if 00 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 00 == datetime.datetime.now().hour and 45 == datetime.datetime.now().minute:
        playsound('3 Quarter Hour Chime.mp3')
        playsound('#.mp3')
    continue
while x == 30:
    print(strftime("%H:%M:%S"), end="", flush=x)
    print("\r", end="", flush=x)
    if 1 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 1 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 2 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 2 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 3 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 3 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 4 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 4 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 5 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 5 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 6 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 6 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 7 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 7 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 8 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 8 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 9 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 9 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 10 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 10 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 11 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 11 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 12 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 12 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 13 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 13 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 14 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 14 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 15 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 15 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 16 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 16 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 17 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 17 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 18 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 18 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 19 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 19 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 20 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 20 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 21 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 21 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 22 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 22 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 23 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 23 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    if 00 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 00 == datetime.datetime.now().hour and 30 == datetime.datetime.now().minute:
        playsound('Half Hour Chime.mp3')
        playsound('#.mp3')
    continue
while x == 60:
    print(strftime("%H:%M:%S"), end="", flush=x)
    print("\r", end="", flush=x)
    if 1 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 2 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 3 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 4 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 5 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 6 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 7 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 8 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 9 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 10 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 11 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 12 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 13 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 14 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 15 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 16 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 17 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 18 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 19 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 20 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 21 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 22 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 23 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    if 00 == datetime.datetime.now().hour and 00 == datetime.datetime.now().minute:
        playsound('Hour Chime.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('Hour Strike.mp3')
        playsound('#.mp3')
    continue
